var WordCloudData = {
    "chinese": [{
        "tag": "自然語言處理",
        "weight": 60
    }, {
        "tag": "資訊管理",
        "weight": 80
    }, {
        "tag": "終端",
        "weight": 56
    }, {
        "tag": "樹狀網路",
        "weight": 34
    }, {
        "tag": "人工智慧",
        "weight": 89
    }, {
        "tag": "遠距學習",
        "weight": 34
    }, {
        "tag": "木馬程式",
        "weight": 25
    }, {
        "tag": "雲端運算",
        "weight": 78
    }, {
        "tag": "資料倉儲",
        "weight": 90
    }, {
        "tag": "倫理",
        "weight": 58
    }, {
        "tag": "光纖網路",
        "weight": 90
    }, {
        "tag": "可行性研究",
        "weight": 45
    }, {
        "tag": "加盟",
        "weight": 90
    }, {
        "tag": "甘特圖",
        "weight": 67
    }, {
        "tag": "駭客",
        "weight": 68
    }, {
        "tag": "資訊不對稱",
        "weight": 58
    }, {
        "tag": "封包過濾",
        "weight": 90
    }, {
        "tag": "共筆",
        "weight": 47
    }, {
        "tag": "資料探勘",
        "weight": 87
    }, {
        "tag": "整合通訊",
        "weight": 34
    }, {
        "tag": "非結構化決策",
        "weight": 22
    }, {
        "tag": "虛擬化",
        "weight": 12
    }, {
        "tag": "供應鏈",
        "weight": 55
    }, {
        "tag": "系統開發生命週期",
        "weight": 67
    }, {
        "tag": "安全",
        "weight": 90
    }, {
        "tag": "廣域網路",
        "weight": 87
    }, {
        "tag": "機器學習",
        "weight": 90
    }, {
        "tag": "長邊效應",
        "weight": 90
    }, {
        "tag": "頻寬",
        "weight": 90
    }, {
        "tag": "變革管理",
        "weight": 21
    }, {
        "tag": "B2B",
        "weight": 90
    }, {
        "tag": "B2C",
        "weight": 92
    }, {
        "tag": "寬頻",
        "weight": 46
    }, {
        "tag": "類別",
        "weight": 55
    }, {
        "tag": "資訊不對稱",
        "weight": 90
    }, {
        "tag": "資訊科技",
        "weight": 90
    }, {
        "tag": "處理",
        "weight": 35
    }, {
        "tag": "整合通訊",
        "weight": 78
    }, {
        "tag": "商業機密",
        "weight": 68
    }, {
        "tag": "外包",
        "weight": 78
    }, {
        "tag": "德菲爾法",
        "weight": 56
    }, {
        "tag": "雙因子理論",
        "weight": 23
    }, {
        "tag": "平衡計分卡",
        "weight": 66
    }, {
        "tag": "組織結構",
        "weight": 89
    }, {
        "tag": "通路",
        "weight": 23
    }, {
        "tag": "全球化",
        "weight": 25
    }, {
        "tag": "主管支援系統",
        "weight": 32
    }],
    "english": [{
        "tag": "executive",
        "weight": 45
    }, {
        "tag": "shareholder",
        "weight": 160
    }, {
        "tag": "consultant",
        "weight": 20
    }, {
        "tag": "receptionist",
        "weight": 78
    }, {
        "tag": "supplier",
        "weight": 60
    }, {
        "tag": "spectator",
        "weight": 38
    }, {
        "tag": "punctuality",
        "weight": 56
    }, {
        "tag": "bulletin",
        "weight": 110
    }, {
        "tag": "extension",
        "weight": 202
    }, {
        "tag": "receptionist",
        "weight": 47
    }, {
        "tag": "capability",
        "weight": 58
    }, {
        "tag": "consultation",
        "weight": 58
    }, {
        "tag": "eligible",
        "weight": 34
    }, {
        "tag": "subsidy",
        "weight": 23
    }, {
        "tag": "promote",
        "weight": 12
    }],
}


var PieData = {
    "September": [{
        "country": "哲學",
        "litres": 501.9
    }, {
        "country": "宗教",
        "litres": 301.9
    }, {
        "country": "自然科學",
        "litres": 201.1
    }, {
        "country": "應用科學",
        "litres": 165.8
    }, {
        "country": "社會科學",
        "litres": 139.9
    }, {
        "country": "中國史地",
        "litres": 128.3
    }, {
        "country": "語文",
        "litres": 99
    }, {
        "country": "藝術",
        "litres": 60
    }, {
        "country": "其他",
        "litres": 50
    }],
    "October": [{
        "country": "哲學",
        "litres": 299
    }, {
        "country": "宗教",
        "litres": 123
    }, {
        "country": "自然科學",
        "litres": 48
    }, {
        "country": "應用科學",
        "litres": 255
    }, {
        "country": "社會科學",
        "litres": 500
    }, {
        "country": "中國史地",
        "litres": 200
    }, {
        "country": "語文",
        "litres": 60
    }, {
        "country": "藝術",
        "litres": 30
    }, {
        "country": "其他",
        "litres": 26
    }],
}